#!/usr/bin/env python
# -*- coding: utf-8 -*-
import re
import sys

import nxstxm_validate as nxv

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    print(sys.argv)

    sys.exit(nxv.validate(sys.argv[1:]))


